{
 "title": "Mongo Streams Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "OpLog Last Seen At",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " max_over_time(sync_last_seen_oplog_at[24h] )"
    }
   ]
  },
  {
   "title": "Sync Last Seen At",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " max_over_time(sync_last_seen_doc_at[24h] )"
    }
   ]
  },
  {
   "title": "Sync Lag (in Seconds)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " (max_over_time(sync_last_seen_oplog_at[24h] ) - ignoring(instance, job)  max_over_time(sync_last_seen_doc_at[24h] ) )/ 1000"
    }
   ]
  },
  {
   "title": "Sync Last Processed At",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " max_over_time(sync_last_processed_doc_at[24h] )"
    }
   ]
  },
  {
   "title": "Process Lag (in Seconds)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " (max_over_time(sync_last_processed_doc_at[24h] ) - max_over_time(sync_last_seen_doc_at[24h] ) )/ 1000"
    }
   ]
  }
 ]
}