global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'mongo-streams-app'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'mongo-streams-monitor'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8081']